name: CI

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.scss"
      - "**/*.json"
      - "package.json"
      - "bun.lock"
      - "biome.json"
      - "tsconfig.json"
      - "tsconfig.app.json"
      - "tsconfig.node.json"
      - "vite.config.*"

  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.scss"
      - "**/*.json"
      - "package.json"
      - "bun.lock"
      - "biome.json"
      - "tsconfig.json"
      - "tsconfig.app.json"
      - "tsconfig.node.json"
      - "vite.config.*"

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Format & Lint (Biome)
        run: bun run check

      - name: Type check (TypeScript)
        run: bun run typecheck
